### ISSUE TITLE
A wish for a wiki entry on reactive application design

### ISSUE THREAD

**Issue by l15k4** [monifu/monifu#31]
Hey Alexandru,

congratulations for merging JVM with JS, I upgraded all my stuff, it works perfectly. 

I'm new to programming apps that have UIs. I feel like I grokked RX at the lower level but I'm still struggling at the higher one, at the application architecture level. I've been using akka for half a year and it was super easy and intuitive to design a reactive application. But when using just RX I can't find the best practice on designing an application that is composed of a few interactive components.

If we consider client-side single page app as a bunch of components (imagine twitter bootstrap grid with 4-6 cells, each one containing a component) that yield events based on user's interaction and they depend on each others events, do you have some sort of proven methodology like : a Hot Channel per component + repushing events to dependend components OR just one main observable shared by (passed along as a constructor arg to) all components, etc. etc. You know what I mean ?

Usually if user clicks at a menu item in Navbar, then it may have impact on three other components sequentially and it may throw error at the second one. This fact makes it quite non-trivial and it makes me thing that the solution is having a main hot channel shared via constructor by all components that may subscribe to it multiple times. It's basically a broadcasting with lots of very long partial functions :-) But it seems to be maintainable and sane. I'm starting to think that RX isn't suitable for this job, at least I'm never quite sure what I'm doing :-)) Maybe I should use scala.rx for the UI part but my head was spinning even more when I used it.

Would you mind write it up a little bit? Or just give me some pointers? I can't find literally nothing on the internets and you seem to be one of a few competent programmers able to do that :-)

UPDATE: 

I think that  [flux](https://github.com/facebook/flux) kinda does what I said. Their dispatcher is like a main hot channel that all components subscribe to in a specific order and any action is dispatched to them accordingly. It's a unidirectional broadcasting with certain order and considering the fact that subscribers may filter out messages they are not interested in, it practically gives you all you need except for bidirectional communication between components which would cause madness anyway :-)

Beyond this pattern, I think that other Observables should be just helpers to deal with asynchronicity, like DB access or Ajax (combineLatest, AsyncSubject, etc). I have a feeling I finally grok RX even at the higher level :-)

**Comment by alexandru** [comment]
I have added this as a mention in issue #27 and closing this one in order to keep the back-log clean.
