### ISSUE TITLE
FlatMap alternative

### ISSUE THREAD

**Issue by l15k4** [monifu/monifu#34]
Given this code and output : 
```scala
"flatMap"- {
  Observable.from(List(1)).doWork(println).doOnComplete(println("1. done")).flatMap { e =>
   println("concatenating " + e)
   Observable.from(List(2)).doWork(println).doOnComplete(println("2. done"))
 }.asFuture
}

1
concatenating 1
2
2. done
1. done
```

I very often need this output
```scala
1
1. done
concatenating 1
2
2. done
```

Basically I'd need current flatMap that would complete observables (if they do) before the actual concatenation...

Is there currently any way to do that? Or should I write a custom operator?

**Comment by alexandru** [comment]
@l15k4 I changed the implementation of `Observable.doOnComplete` to be synchronous, so it will execute before the `onComplete` is signaled to the final observer.

The semantics of `doOnComplete` changed though. It doesn't take care of cancelation or errors for example. 2 operators where introduced for that, `doOnError` and `doOnCanceled` respectively.

Version 1.0-M1 is now on Maven Central. Take it for a spin :-)
