### ISSUE TITLE
Missing way to observe Either of two observables?

### ISSUE THREAD

**Issue by BardurArantsson** [monifu/monifu#48]
Hi,

I'm probably missing something, but it seems that Monifu lacks a built-in combinator for selecting Either of two observables, i.e. a function from (Observable[A], Observable[B]) => Observable[Either[A,B]] which would "trigger" when either of the two observables does.

Is it just an oversight, or are users supposed to implement it on their own? If the latter, how you suggest implementing it?

Regards,

**Comment by alexandru** [comment]
@BardurArantsson what would be the equivalent operator in Rx?

Also, you can do it like this ...

```scala
val oa = Observable.from("a", "b", "c").map(Left.apply)
val ob = Observable.from(1, 2, 3).map(Right.apply)
  
val merged = Observable.from(oa, ob).merge()
```

Do you need something else?

**Comment by BardurArantsson** [comment]
Oh, right! If I understand merge() correctly, then that will indeed do what I want. I guess I'm  just not used to thinking in terms of Observables of Observables yet :).

Thank you for the help!
