### ISSUE TITLE
Sample an Observable by another one

### ISSUE THREAD

**Issue by dimitriho** [monifu/monifu#49]
I'm looking for something similar to the [`sample`](http://reactivex.io/rxscala/scaladoc/index.html#rx.lang.scala.Observable@sample(sampler:rx.lang.scala.Observable[Any]):rx.lang.scala.Observable[T]) method in RxScala's Observable. Is there an easy way to achieve this with the current API of monifu?

**Comment by alexandru** [comment]
Currently that `sample` variant is not implemented because I couldn't find a use-case for it yet.
But I can implement it for the next release, if you'll be patient :-)

Leaving this open.

**Comment by alexandru** [comment]
@dimitriho, sample's implementation has been refactored and a `sample(sampler: Observable)` variant is now in master. Will be available in the next deployed version.

Cheers,

**Comment by dimitriho** [comment]
Nice! thanks @alexandru :)
