### ISSUE TITLE
Delay with specific time delay

### ISSUE THREAD

**Issue by mfirry** [monifu/monifu#81]
Hi,
I'm trying to use monifu with the following use case:
all elements bring with themselves a time value and I basically need to wait that amount of time before going further the following element.

I hope this makes sense :)

I'm trying to accomplish this by using the `scheduler` and `scheduleOnce(delay)` but cannot fully make it work.

I'm also new to Rx in general so I might be asking a silly question.

**Comment by alexandru** [comment]
Don't use the scheduler directly. Do it like this ...

```scala
observable.flatMap { elem =>
  Observable.unit(elem).delaySubscription(elem.delay)
}
```

Let me know if that answers your question.

**Comment by mfirry** [comment]
This is a great advice. Thanks. You can close this. I'll re-open it if I need more help.

**Comment by alexandru** [comment]
Cool :-)
